apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify-volume-claim
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
