services:
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:0.3.0
    devices:
      - "/dev/dri:/dev/dri"
    env_file: .env
    volumes:
      - ${APPDATA_PATH}/unmanic/config:/config
      - ${DATA_PATH}:/data
      - /dev/shm/unmanic:/tmp/unmanic
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.unmanic.tls: true
      traefik.http.routers.unmanic.tls.certresolver: letsencrypt
      traefik.http.routers.unmanic.rule: Host(`${SERVICE_URL}`)
      traefik.http.routers.unmanic.entrypoints: websecure
      traefik.http.routers.unmanic.middlewares: tinyauth

      tinyauth.domain: ${SERVICE_URL}
      tinyauth.oauth.groups: admin

      glance.name: Unmanic
      glance.icon: sh:unmanic
      glance.url: https://${SERVICE_URL}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/unmanic.png
      net.unraid.docker.webui: https://${SERVICE_URL}
networks:
  proxy:
    external: true