[[server]]
name = "nas"
[server.config]
address = "https://periphery:8120"
enabled = true

##

[[repo]]
name = "selfhosted"
[repo.config]
server = "nas"
builder = "local"
repo = "joostme/selfhosted"

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server_id = "nas"

##

[[resource_sync]]
name = "git-sync"
[resource_sync.config]
linked_repo = "selfhosted"
resource_path = [
  "komodo/config.toml",
  "komodo/stacks.toml"
]
delete = true

[[procedure]]
name = "deploy-changed"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "RunSync", execution.params.sync = "git-sync", enabled = true },
  { execution.type = "PullRepo", execution.params.repo = "selfhosted", enabled = true }
]

[[procedure.config.stage]]
name = "Stage 2"
enabled = true
executions = [
  { execution.type = "BatchDeployStackIfChanged", execution.params.pattern = "*", enabled = true }
]
