[[server]]
name = "nas"
[server.config]
address = "https://periphery:8120"
enabled = true

##

[[repo]]
name = "selfhosted"
[repo.config]
server = "nas"
builder = "local"
repo = "joostme/selfhosted"

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server_id = "nas"

##

[[resource_sync]]
name = "git-sync"
[resource_sync.config]
linked_repo = "selfhosted"
resource_path = [
  "komodo/config.toml",
  "services/adguard/stack.toml",
  "services/arr/stack.toml",
  "services/asf/stack.toml",
  "services/audiobookshelf/stack.toml",
  "services/calibre/stack.toml",
  "services/dozzle/stack.toml",
  "services/glance/stack.toml",
  "services/immich/stack.toml",
  "services/jellyfin/stack.toml",
  "services/paperless/stack.toml",
  "services/redis/stack.toml",
  "services/syncthing/stack.toml",
  "services/tandoor/stack.toml",
  "services/teddycloud/stack.toml",
  "services/traefik/stack.toml",
  "services/tubearchivist/stack.toml",
]
