services:
  mongo:
    image: mongo:8.0.13
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    # ports:
    #   - 27017:27017
    volumes:
      - ${APPDATA_PATH}/komodo/mongo/db:/data/db
      - ${APPDATA_PATH}/komodo/mongo/config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}
    env_file: .env
    networks:
      - komodo
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
      glance.parent: komodo
      glance.name: KomogoMongo
      glance.icon: sh:mongodb
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/mongodb.png
  
  core:
    image: ghcr.io/moghtech/komodo-core:1.19.4
    restart: unless-stopped
    depends_on:
      - mongo
    # ports:
    #  - 9120:9120
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
    env_file: ./.env
    volumes:
      - ${APPDATA_PATH}/komodo/core/backups:/backups
    networks:
      - proxy
      - komodo
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers

      traefik.enable: true
      traefik.http.routers.komodo.tls: true
      traefik.http.routers.komodo.tls.certresolver: letsencrypt
      traefik.http.routers.komodo.rule: Host(`${SERVICE_URL_KOMODO}`)
      traefik.http.routers.komodo.entrypoints: websecure

      glance.id: komodo
      glance.name: Komodo
      glance.icon: sh:komodo
      glance.url: https://${SERVICE_URL_KOMODO}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/komodo.png
      net.unraid.docker.webui: https://${SERVICE_URL_KOMODO}

  periphery:
    image: ghcr.io/moghtech/komodo-periphery:1.19.4
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
    env_file: ./.env
    networks:
      - komodo
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
      glance.parent: komodo
      glance.name: KomodoPeriphery
      glance.icon: sh:komodo
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/komodo.png

networks:
  komodo:
  proxy:
    external: true