services:
  teddycloud:
    container_name: teddycloud
    image: ghcr.io/toniebox-reverse-engineering/teddycloud:tc_v0.6.4
    restart: always
    volumes:
      - ${APPDATA_PATH}/teddycloud/data/content:/teddycloud/data/content
      - ${APPDATA_PATH}/teddycloud/config:/teddycloud/config
      - ${APPDATA_PATH}/teddycloud/certs:/teddycloud/certs
      - ${MNT_PATH}/teddycloud_library/:/teddycloud/data/library
      - ${APPDATA_PATH}/teddycloud/data/firmware:/teddycloud/data/firmware
    env_file: .env
    networks:
      br0:
        ipv4_address: ${TEDDYCLOUD_IP}
      proxy:
    labels:
      traefik.enable: true
      traefik.http.routers.teddycloud.tls: true
      traefik.http.routers.teddycloud.tls.certresolver: letsencrypt
      traefik.http.routers.teddycloud.rule: Host(`${SERVICE_URL}`)
      traefik.http.routers.teddycloud.entrypoints: websecure
      traefik.http.routers.teddycloud.service: teddycloud
      traefik.http.services.teddycloud.loadbalancer.server.port: 80
      traefik.http.routers.teddycloud.middlewares: tinyauth

      tinyauth.apps.teddycloud.config.domain: ${SERVICE_URL}
      tinyauth.apps.teddycloud.oauth.groups: admin

      glance.name: Teddycloud
      glance.icon: sh:teddycloud
      glance.url: https://${SERVICE_URL}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/teddycloud.png
      net.unraid.docker.webui: https://${SERVICE_URL}
networks:
  br0:
    external: true
  proxy:
    external: true
