[[stack]]
name = "teddycloud"
[stack.config]
server = "nas"
linked_repo = "selfhosted"
run_directory = "services/teddycloud"
file_paths = ["docker-compose.yml"]
environment = """
DOMAIN=[[DOMAIN]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
UMASK=[[UMASK]]
MNT_PATH=[[MNT_PATH]]
APPDATA_PATH=[[APPDATA_PATH]]
DATA_PATH=[[DATA_PATH]]

TEDDYCLOUD_IP=[[TEDDYCLOUD_IP]]
SERVICE_URL=teddycloud.[[DOMAIN]]
"""