services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:v1.9.10'
    ports:
      - '7777:7777/tcp'
      - '7777:7777/udp'
      - '8888:8888/tcp'
    volumes:
      - '${APPDATA_PATH}/satisfactory-server:/config'
    env_file:
      - .env
    restart: unless-stopped
    networks:
      br0:
        ipv4_address: ${SATISFACTORY_IP}
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    labels:
      glance.name: Satisfactory Server

networks:
  br0:
    external: true