services:
  tubearchivist:
    container_name: tubearchivist
    image: bbilly1/tubearchivist:v0.5.7
    restart: unless-stopped
    volumes:
      - ${APPDATA_PATH}/tubearchivist/cache:/cache
      - ${MNT_PATH}/tubearchivist:/youtube
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - tubearchivist
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.tubearchivist.tls: true
      traefik.http.routers.tubearchivist.tls.certresolver: letsencrypt
      traefik.http.routers.tubearchivist.rule: Host(`${SERVICE_URL}`)
      traefik.http.routers.tubearchivist.entrypoints: websecure
      traefik.http.routers.tubearchivist.middlewares: tinyauth
      
      tinyauth.apps.tubearchivist.config.domain: ${SERVICE_URL}
      tinyauth.apps.tubearchivist.oauth.groups: admin

      glance.id: tubearchivist
      glance.name: TubeArchivist
      glance.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/tube-archivist.png # no svg icon for TA on sh: icons
      glance.url: https://${SERVICE_URL}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/tube-archivist.png
      net.unraid.docker.webui: https://${SERVICE_URL}
    depends_on:
      - archivist-redis
      - archivist-es
  
  archivist-redis:
    image: redis:8.2.2
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - ${APPDATA_PATH}/tubearchivist/redis:/data
    depends_on:
      - archivist-es
    networks:
      - tubearchivist
    labels:
      glance.name: Redis
      glance.icon: sh:redis
      glance.parent: tubearchivist
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/redis.png

  archivist-es:
    image: bbilly1/tubearchivist-es:8.18.2
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=verysecret"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data
    expose:
      - "9200"
    networks:
      - tubearchivist
    labels:
      glance.name: ElasticSearch
      glance.icon: sh:elasticsearch
      glance.parent: tubearchivist
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/elasticsearch.png

volumes:
  es:

networks:
  tubearchivist:
  proxy:
    external: true
  redis_net:
    external: true
