[[stack]]
name = "tubearchivist"
[stack.config]
server = "nas"
linked_repo = "selfhosted"
run_directory = "services/tubearchivist"
file_paths = ["docker-compose.yml"]
environment = """
DOMAIN=[[DOMAIN]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
UMASK=[[UMASK]]
MNT_PATH=[[MNT_PATH]]
APPDATA_PATH=[[APPDATA_PATH]]
DATA_PATH=[[DATA_PATH]]


TA_HOST=https://tubearchivist.${DOMAIN}
TA_USERNAME=admin
TA_PASSWORD=changeme
HOST_UID=${PUID}
HOST_GID=${PGID}
REDIS_CON=redis://archivist-redis:6379
ES_URL=http://archivist-es:9200
ELASTIC_PASSWORD=verysecret

SERVICE_URL=tubearchivist.[[DOMAIN]]
"""