services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:v0.107.64
    restart: always
    volumes:
      - ${APPDATA_PATH}/adguard/workingdir:/opt/adguardhome/work
      - ${APPDATA_PATH}/adguard/config:/opt/adguardhome/conf
    networks:
      br0:
        ipv4_address: ${ADGUARD_IP}
      proxy:
    labels:
      traefik.enable: true
      traefik.http.routers.adguard.tls: true
      traefik.http.routers.adguard.rule: Host(`adguard.${DOMAIN}`)
      traefik.http.routers.adguard.entrypoints: websecure
      traefik.http.routers.adguard.service: adguard
      traefik.http.services.adguard.loadbalancer.server.port: 80

      glance.id: adguard
      glance.name: Adguard
      glance.icon: sh:adguard-home
      glance.url: https://adguard.${DOMAIN}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/adguard-home.png
      net.unraid.docker.webui: http://adguard.${DOMAIN}

  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync:v0.7.8
    container_name: adguardhome-sync
    command: run
    restart: unless-stopped
    env_file: .env
    networks:
      - proxy
    labels:
      glance.parent: adguard
      glance.icon: sh:adguardhome-sync
      glance.url: https://adguard-sync.${DOMAIN}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/adguardhome-sync.png
      net.unraid.docker.webui: http://adguard-sync.${DOMAIN}

networks:
  br0:
    external: true
  proxy:
    external: true
