services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome
    restart: always
    volumes:
      - ${APPDATA_PATH}/adguard/workingdir:/opt/adguardhome/work
      - ${APPDATA_PATH}/adguard/config:/opt/adguardhome/conf
    networks:
      br0:
        ipv4_address: ${ADGUARD_IP}
      npm_net:
    labels:
      glance.name: Adguard
      glance.icon: sh:adguard-home
      glance.url: https://adguard.${DOMAIN}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/adguard-home.png
      net.unraid.docker.webui: http://adguard.${DOMAIN}

  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguardhome-sync
    command: run
    restart: unless-stopped
    env_file: stack.env
    networks:
      - npm_net

networks:
  br0:
    external: true
  npm_net:
    external: true
