version: "3.4"
services:
  heimdall:
    image: linuxserver/heimdall:latest
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - config:/config
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.heimdall_https.entrypoints=websecure"
      - "traefik.http.routers.heimdall_https.rule=Host(`heimdall.joost.io`)"
      - "traefik.http.routers.heimdall_https.tls=true"
      - "traefik.http.routers.heimdall_https.tls.certresolver=myresolver"
      - "traefik.http.routers.heimdall_https.service=heimdall"
      
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"
  
networks:
  traefik:
    external: true

volumes:
  config: