# yamllint disable rule:comments-indentation
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

## The theme to display: light, dark, grey, auto.
theme: auto

# jwt_secret: provided by ENV

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  disable_healthcheck: false


log:
  level: info
  format: json
  file_path: /data/authelia.log
  keep_stdout: false

totp:
  disable: true

webauthn:
  disable: true


authentication_backend:
  file:
    path: /data/users_database.yml


access_control:
  default_policy: deny

  rules:
    - domain: '*.joost.io'
      policy: one_factor


session:
  # secret: provided in ENV
  domain: joost.io

storage:
  # encryption_key: provided in ENV

  local:
    path: /data/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: /data/notification.txt