services:
  asf:
    container_name: asf
    image: justarchi/archisteamfarm:6.2.2.0
    restart: always
    env_file: .env
    volumes:
      - ${APPDATA_PATH}/asf/config:/app/config
      - ${APPDATA_PATH}/asf/plugins:/app/plugins
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.asf.tls: true
      traefik.http.routers.asf.tls.certresolver: letsencrypt
      traefik.http.routers.asf.rule: Host(`${SERVICE_URL}`)
      traefik.http.routers.asf.entrypoints: websecure
      traefik.http.routers.asf.middlewares: authentik@docker

      glance.name: ASF
      glance.icon: sh:steam
      glance.url: https://${SERVICE_URL}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/steam.png
      net.unraid.docker.webui: https://${SERVICE_URL}

networks:
  proxy:
    external: true