apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
  namespace: adguard
spec:
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      # Workaround to ConfigMap volumes being write only.
      initContainers:
        - name: adguard-copy-config
          image: alpine
          command:
            - sh
            - -c
          args:
            - cp /mnt/config/AdGuardHome.yaml /mnt/config-rw
          volumeMounts:
            - name: adguard-config
              mountPath: '/mnt/config'
            - name: adguard-config-rw
              mountPath: '/mnt/config-rw'
      containers:
        - name: adguard
          image: adguard/adguardhome
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: http
              containerPort: 80
          volumeMounts:
            - name:  adguard-config-rw
              mountPath: '/opt/adguardhome/conf'
          livenessProbe:
            exec:
              command:
                - nslookup
                - 'adguard.dns'
                - '127.0.0.1'
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 3
      volumes:
        - name: adguard-config
          configMap:
            name: adguard-config
            items:
              - key: adguard.yaml
                path: AdGuardHome.yaml
        - name: adguard-config-rw
          emptyDir: {}
 

