apiVersion: v1
kind: Service
metadata:
  name: adguard-http
  namespace: adguard
spec:
  selector:
    app: adguard
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
---
kind: Service
apiVersion: v1
metadata:
  name: adguard-dns-udp
  namespace: adguard
spec:
  selector:
    app: adguard
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port:  53
      targetPort:  dns-udp
      protocol: UDP
      name: dns-udp