version: "3.4"
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    restart: unless-stopped
    network_mode: host
    volumes:
      - config:/config
    labels:
      - "traefik.enable=true"
      
      - "traefik.http.routers.homeassistant_https.entrypoints=websecure"
      - "traefik.http.routers.homeassistant_https.rule=Host(`homeassistant.joost.io`)"
      - "traefik.http.routers.homeassistant_https.tls=true"
      - "traefik.http.routers.homeassistant_https.tls.certresolver=myresolver"
      - "traefik.http.routers.homeassistant_https.service=homeassistant"

      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
  
volumes:
  config: