version: "3.4"
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    restart: unless-stopped
    network_mode: host
    volumes:
      - config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.joost.ioassistant.rule=Host(`homeassistant.joost.io`)"
      - "traefik.http.services.joost.ioassistant.loadbalancer.server.port=8123"
  
volumes:
  config: