version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true
      - WEB_VAULT_ENABLED=true
      - SIGNUPS_ALLOWED=false
    env_file:
      - ./.env
    volumes:
      - ./data:/data
    logging:
      driver: journald
      options:
        tag: vaultwarden
networks:
  default:
    external: true
    name: npm