version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    networks:
      - default

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    networks:
      - default

  webserver:
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - /mnt/Dokumente:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_CONSUMER_POLLING: 300
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless_https.entrypoints=websecure"
      - "traefik.http.routers.paperless_https.rule=Host(`paperless.joost.io`)"
      - "traefik.http.routers.paperless_https.tls=true"
      - "traefik.http.routers.paperless_https.tls.certresolver=myresolver"
      - "traefik.http.routers.paperless_https.service=adguard"
      - "traefik.http.services.paperless_https.loadbalancer.server.port=8000"


      - "traefik.http.routers.paperless_http.entrypoints=web"
      - "traefik.http.routers.paperless_http.rule=Host(`paperless.joost.io`)"
      - "traefik.http.routers.paperless_http.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
    networks:
      - default
      - traefik


volumes:
  pgdata:
  data:
  
networks:
  default:
  traefik:
    external: true