version: "3.4"
services:
  traefik:
    image: traefik:v2.6
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.joost.io`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
  
networks:
  traefik:
    external: true