version: "3.8"
secrets:
  JWT_SECRET:
    file: ./authelia/secrets/JWT_SECRET
  SESSION_SECRET:
    file: ./authelia/secrets/SESSION_SECRET
  STORAGE_ENCRYPTION_KEY:
    file: ./authelia/secrets/STORAGE_ENCRYPTION_KEY
services:
  traefik:
    image: traefik:v2.9
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./dynamic.yml:/etc/traefik/dynamic.yml
      - ./acme.json:/acme.json
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.traefik_https.entrypoints=websecure"
      - "traefik.http.routers.traefik_https.rule=Host(`traefik.joost.io`)"
      - "traefik.http.routers.traefik_https.tls=true"
      - "traefik.http.routers.traefik_https.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik_https.service=api@internal"
      - "traefik.http.routers.traefik_https.tls.domains[0].main=joost.io"
      - "traefik.http.routers.traefik_https.tls.domains[0].sans=*.joost.io"
      - "traefik.http.routers.traefik_https.middlewares=authelia@docker"

      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

      - 'traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https%3A%2F%2Fauth.joost.io%2F'
      - 'traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'

      - "com.centurylinklabs.watchtower.enable=true"
    # Extra Hosts for HomeAssistant mapping. As HA is running in host mode, it would map top 127.0.0.1
    extra_hosts:
      - host.docker.internal:172.17.0.1
    depends_on:
      - authelia

  authelia:
    container_name: authelia
    image: authelia/authelia
    restart: unless-stopped
    networks:
      - traefik
    expose:
      - 9091
    volumes:
      - ./authelia/config:/config
      - ./data/authelia:/data
    environment:
      TZ: "Europe/Berlin"
      AUTHELIA_JWT_SECRET_FILE: /run/secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/SESSION_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/STORAGE_ENCRYPTION_KEY
    secrets: [JWT_SECRET, SESSION_SECRET, STORAGE_ENCRYPTION_KEY]
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`auth.joost.io`)'
      - 'traefik.http.routers.authelia.entryPoints=websecure'
      - 'traefik.http.routers.authelia.tls=true'

      - "com.centurylinklabs.watchtower.enable=true"

networks:
  traefik:
    external: true