version: "3.4"
services:
  traefik:
    image: traefik:v2.6
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.traefik_https.entrypoints=websecure"
      - "traefik.http.routers.traefik_https.rule=Host(`traefik.joost.io`)"
      - "traefik.http.routers.traefik_https.tls=true"
      - "traefik.http.routers.traefik_https.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik_https.service=api@internal"

      - "traefik.http.routers.traefik_http.entrypoints=web"
      - "traefik.http.routers.traefik_http.rule=Host(`traefik.joost.io`)"
      - "traefik.http.routers.traefik_http.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
  
networks:
  traefik:
    external: true