http:
  routers:
    adguard:
      entryPoints:
        - "websecure"
      rule: "Host(`adguard.joost.io`)"
      tls:
        certResolver: myresolver
      service: adguard
    homeassistant:
      entryPoints:
        - "websecure"
      rule: "Host(`home.joost.io`)"
      tls:
        certResolver: myresolver
      service: homeassistant

  services:
    adguard:
      loadBalancer:
        servers:
          - url: "http://10.0.0.33:80"
        passHostHeader: true
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://10.0.0.45:8123"
        passHostHeader: true