version: '3.2'
services:
    changedetection:
      image: ghcr.io/dgtlmoon/changedetection.io
      container_name: changedetection
      hostname: changedetection
      volumes:
        - ./data:/datastore
      env_file:
        - ./.env
      environment:
        - PUID=1000
        - PGID=1000
        - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000/?stealth=1&--disable-web-security=true
        - USE_X_SETTINGS=1
        - HIDE_REFERER=true
      restart: unless-stopped
      depends_on:
        playwright-chrome:
          condition: service_started

    playwright-chrome:
      hostname: playwright-chrome
      image: browserless/chrome
      restart: unless-stopped
      environment:
          - SCREEN_WIDTH=1920
          - SCREEN_HEIGHT=1024
          - SCREEN_DEPTH=16
          - ENABLE_DEBUGGER=false
          - PREBOOT_CHROME=true
          - CONNECTION_TIMEOUT=300000
          - MAX_CONCURRENT_SESSIONS=10
          - CHROME_REFRESH_TIME=600000
          - DEFAULT_BLOCK_ADS=true
          - DEFAULT_STEALTH=true
          - DEFAULT_IGNORE_HTTPS_ERRORS=true

networks:
  default:
    external: true
    name: npm