services:
  syncthing:
    container_name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    restart: always
    volumes:
      - ${MNT_PATH}/Syncthing:/data
      - ${APPDATA_PATH}/syncthing:/config"
    ports:
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    env_file: .env
    networks:
      - proxy
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      traefik.enable: true
      traefik.http.routers.syncthing.tls: true
      traefik.http.routers.syncthing.tls.certresolver: letsencrypt
      traefik.http.routers.syncthing.rule: Host(`${SERVICE_URL}`)
      traefik.http.routers.syncthing.entrypoints: websecure
      traefik.http.routers.syncthing.service: syncthing
      traefik.http.services.syncthing.loadbalancer.server.port: 8384

      glance.name: Syncthing
      glance.icon: sh:syncthing
      glance.url: https://${SERVICE_URL}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/syncthing.png
      net.unraid.docker.webui: https://${SERVICE_URL}
networks:
  proxy:
    external: true
