[[stack]]
name = "syncthing"
[stack.config]
server = "nas"
linked_repo = "selfhosted"
run_directory = "services/syncthing"
file_paths = ["docker-compose.yml"]
environment = """
MNT_PATH=[[MNT_PATH]]
APPDATA_PATH=[[APPDATA_PATH]]
PUID=[[PUID]]
PGID=[[PGID]]
DOMAIN=[[DOMAIN]]
SERVICE_URL=syncthing.[[DOMAIN]]
"""