services:
  forgejo:
    container_name: forgejo
    image: codeberg.org/forgejo/forgejo:16.0.4
    restart: unless-stopped
    volumes:
      - ${APPDATA_PATH}/forgejo/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
    environment:
      - USER_UID=${PUID}
      - USER_GID=${PGID}
      - FORGEJO__actions__ENABLED=true
      - FORGEJO__webhook__ALLOWED_HOST_LIST=private,*.${DOMAIN}
      - FORGEJO__server__ROOT_URL=https://${SERVICE_URL}
      - FORGEJO__server__DOMAIN=${SERVICE_URL}
      - FORGEJO__server__SSH_DOMAIN=${SERVICE_URL}
    labels:
      traefik.enable: true
      traefik.http.routers.forgejo.tls: true
      traefik.http.routers.forgejo.tls.certresolver: letsencrypt
      traefik.http.routers.forgejo.rule: Host(`${SERVICE_URL}`)
      traefik.http.routers.forgejo.entrypoints: websecure
      traefik.http.routers.forgejo.service: forgejo
      traefik.http.services.forgejo.loadbalancer.server.port: 3000

      glance.name: Forgejo
      glance.icon: sh:forgejo
      glance.url: https://${SERVICE_URL}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/forgejo.png
      net.unraid.docker.webui: https://${SERVICE_URL}

  forgejo-dind:
    container_name: forgejo-dind
    image: docker:29.8.0-dind
    restart: unless-stopped
    privileged: true
    command: dockerd --host=tcp://0.0.0.0:2375 --tls=false
    volumes:
      - ${APPDATA_PATH}/forgejo/dind:/var/lib/docker
    networks:
      - forgejo-runner

  forgejo-runner:
    container_name: forgejo-runner
    image: data.forgejo.org/forgejo/runner:13.1.0
    restart: unless-stopped
    depends_on:
      forgejo-dind:
        condition: service_started
    environment:
      DOCKER_HOST: tcp://forgejo-dind:2375
    user: "${PUID}:${PGID}"
    working_dir: /data
    command: forgejo-runner daemon --config /data/runner-config.yml
    volumes:
      - ${APPDATA_PATH}/forgejo/runner:/data
    networks:
      - forgejo-runner
networks:
  proxy:
    external: true
  forgejo-runner:
    driver: bridge
