services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - /mnt/user/appdata/npm/data:/data
      - /mnt/user/appdata/npm/letsencrypt:/etc/letsencrypt
      - /tmp/npm/var/log:/var/log
    environment:
      DB_SQLITE_FILE: /data/database.sqlite
    networks:
      br0:
        ipv4_address: ${NPM_IP}
      npm_net:
    labels:
      glance.name: NPM
      glance.icon: sh:nginx-proxy-manager
      glance.category: homelab
      glance.url: http://${NPM_IP}:81
      net.unraid.docker.icon: https://nginxproxymanager.com/icon.png
      net.unraid.docker.webui: "http://[IP]:[PORT:81]"
networks:
  npm_net:
    external: true
  br0:
    external: true
    