[[stack]]
name = "arr"
[stack.config]
server = "nas"
linked_repo = "selfhosted"
run_directory = "services/arr"
file_paths = ["docker-compose.yml"]
environment = """
DOMAIN=[[DOMAIN]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
UMASK=[[UMASK]]
APPDATA_PATH=[[APPDATA_PATH]]
DATA_PATH=[[DATA_PATH]]

SERVICE_URL_SONARR=sonarr.[[DOMAIN]]
SERVICE_URL_RADARR=radarr.[[DOMAIN]]
SERVICE_URL_LIDARR=lidarr.[[DOMAIN]]
SERVICE_URL_SABNZBD=sabnzbd.[[DOMAIN]]
SERVICE_URL_DELUGE=deluge.[[DOMAIN]]
"""