[[stack]]
name = "immich"
[stack.config]
server = "nas"
linked_repo = "selfhosted"
run_directory = "services/immich"
file_paths = ["docker-compose.yml"]
environment = """
DB_HOSTNAME=postgres_immich
DB_USERNAME=postgres
DB_PASSWORD=[[IMMICH_DB_PASS]]
DB_DATABASE_NAME=immich
DB_PORT=5432
REDIS_HOSTNAME=redis
REDIS_PORT=6379
SERVER_HOST=0.0.0.0

MACHINE_LEARNING_HOST=0.0.0.0
MACHINE_LEARNING_PORT=3003
MACHINE_LEARNING_WORKERS=1
MACHINE_LEARNING_WORKER_TIMEOUT=120

POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_USER=postgres
POSTGRES_DB=immich

DOMAIN=[[DOMAIN]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
UMASK=[[UMASK]]
MNT_PATH=[[MNT_PATH]]
APPDATA_PATH=[[APPDATA_PATH]]
DATA_PATH=[[DATA_PATH]]
SERVICE_URL=immich.[[DOMAIN]]
"""