version: "3.4"
services:
  adguard:
    image: adguard/adguardhome:latest
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - work:/opt/adguardhome/work
      - conf:/opt/adguardhome/conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`adguard.home`)"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"
  
networks:
  traefik:
    external: true

volumes:
  work:
  conf: