version: "3.4"
services:
  adguard:
    image: adguard/adguardhome:latest
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./data/work:/opt/adguardhome/work
      - ./data/conf:/opt/adguardhome/conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard_https.entrypoints=websecure"
      - "traefik.http.routers.adguard_https.rule=Host(`adguard.joost.io`)"
      - "traefik.http.routers.adguard_https.tls=true"
      - "traefik.http.routers.adguard_https.tls.certresolver=myresolver"
      - "traefik.http.routers.adguard_https.service=adguard"

      - "traefik.http.services.adguard.loadbalancer.server.port=80"

      - "com.centurylinklabs.watchtower.enable=true"
networks:
  traefik:
    external: true