services:
  traefik:
    container_name: traefik
    image: traefik
    command:
      # Docker
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.asdefault=true"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN}"

      # Certs
      - "--certificatesresolvers.letsencrypt=true"
      - "--certificatesresolvers.letsencrypt.acme.email=webmaster@${DOMAIN}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/certificates/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=porkbun"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1,1.0.0.1"

      # Dashboard
      - "--api=true"
      - "--log.level=DEBUG"
    restart: always
    volumes:
      - $PWD/traefik.yaml:/etc/traefik/traefik.yml
      - certificates:/certificates
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      proxy:
      br0:
        ipv4_address: ${TRAEFIK_IP}
    environment: 
      PORKBUN_API_KEY: ${PORKBUN_API_KEY}
      PORKBUN_SECRET_API_KEY: ${PORKBUN_SECRET_API_KEY}
    labels:
      #traefik.enable: true
      #traefik.http.routers.dashboard.rule: Host(`traefik.${DOMAIN}`)
      #traefik.http.routers.dashboard.entrypoints: websecure
      #traefik.http.routers.dashboard.service: api@internal
      #traefik.http.routers.dashboard.tls: true

      glance.name: Traefik
      glance.icon: sh:traefik
      glance.url: https://traefik.${DOMAIN}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/traefik.png
      net.unraid.docker.webui: https://traefik.${DOMAIN}
networks:
  proxy:
    external: true
  br0:
    external: true

volumes:
  certificates:
    name: certificates