services:
  traefik:
    container_name: traefik
    image: traefik
    restart: always
    volumes:
      - $PWD/traefik.yaml:/etc/traefik/traefik.yaml
      - certificates:/certificates
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      proxy:
      br0:
        ipv4_address: ${TRAEFIK_IP}
    environment:
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL: "webmaster@${DOMAIN}"
      TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_DOMAINS_0_MAIN: "${DOMAIN}"
      TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_DOMAINS_0_SANS: "*.${DOMAIN}"
      PORKBUN_API_KEY: ${PORKBUN_API_KEY}
      PORKBUN_SECRET_API_KEY: ${PORKBUN_SECRET_API_KEY}
    labels:
      #traefik.enable: true
      #traefik.http.routers.dashboard.rule: Host(`traefik.${DOMAIN}`)
      #traefik.http.routers.dashboard.entrypoints: websecure
      #traefik.http.routers.dashboard.service: api@internal
      #traefik.http.routers.dashboard.tls: true

      glance.name: Traefik
      glance.icon: sh:traefik
      glance.url: https://traefik.${DOMAIN}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/traefik.png
      net.unraid.docker.webui: https://traefik.${DOMAIN}
networks:
  proxy:
    external: true
  br0:
    external: true

volumes:
  certificates:
    name: certificates