services:
  portainer:
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/user/appdata/portainer:/data
    image: portainer/portainer-ce:lts
    networks:
      - npm_net
    labels:
      glance.name: Portainer
      glance.icon: sh:portainer
      glance.url: https://portainer.${DOMAIN}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/portainer.png
      net.unraid.docker.webui: https://portainer.${DOMAIN}
networks:
  npm_net:
    external: true
