services:
  glance:
    container_name: glance
    image: glanceapp/glance:v0.8.4
    restart: always
    volumes:
      - ${APPDATA_PATH}/glance/config:/app/config/
      - ${APPDATA_PATH}/glance/assets:/app/assets
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    env_file: .env
    labels:
      traefik.enable: true
      traefik.http.routers.glance.tls: true
      traefik.http.routers.glance.tls.certresolver: letsencrypt
      traefik.http.routers.glance.rule: Host(`${SERVICE_URL}`)
      traefik.http.routers.glance.entrypoints: websecure
      traefik.http.routers.dozzle.middlewares: authentik@docker

      glance.name: Glance
      glance.icon: sh:glance
      glance.url: https://${SERVICE_URL}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/glance.png
      net.unraid.docker.webui: https://${SERVICE_URL}
networks:
  proxy:
    external: true
