[[stack]]
name = "glance"
[stack.config]
server = "nas"
linked_repo = "selfhosted"
run_directory = "services/glance"
file_paths = ["docker-compose.yml"]
environment = """
DOMAIN=[[DOMAIN]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
UMASK=[[UMASK]]
MNT_PATH=[[MNT_PATH]]
APPDATA_PATH=[[APPDATA_PATH]]
DATA_PATH=[[DATA_PATH]]
SERVICE_URL=glance.[[DOMAIN]]
"""