services:
  calibre:
    image: crocodilestick/calibre-web-automated:V3.1.4
    container_name: calibre
    restart: unless-stopped
    volumes:
      - ${APPDATA_PATH}/calibre/config:/config
      - ${APPDATA_PATH}/calibre/ingest/:/cwa-book-ingest
      - ${APPDATA_PATH}/calibre/library:/calibre-library 
    env_file: .env
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.calibre.tls: true
      traefik.http.routers.calibre.tls.certresolver: letsencrypt
      traefik.http.routers.calibre.rule: Host(`${SERVICE_URL_CALIBRE}`)
      traefik.http.routers.calibre.entrypoints: websecure

      glance.name: Calibre-Web
      glance.icon: sh:calibre-web
      glance.url: https://${SERVICE_URL_CALIBRE}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/calibre-web.png
      net.unraid.docker.webui: https://${SERVICE_URL_CALIBRE}

  calibre-vnc:
    image: lscr.io/linuxserver/calibre:8.10.0
    container_name: calibre-vnc
    security_opt:
      - seccomp:unconfined
    env_file: .env
    environment:
      DRINODE: /dev/dri/renderD128
    volumes:
      - ${APPDATA_PATH}/calibre/library:/config
    restart: unless-stopped
    networks:
      - proxy
    devices:
      - "/dev/dri:/dev/dri"
    labels:
      traefik.enable: true
      traefik.http.routers.calibre-vnc.tls: true
      traefik.http.routers.calibre-vnc.tls.certresolver: letsencrypt
      traefik.http.routers.calibre-vnc.rule: Host(`${SERVICE_URL_CALIBRE_VNC}`)
      traefik.http.routers.calibre-vnc.entrypoints: websecure
      traefik.http.routers.calibre-vnc.service: calibre-vnc
      traefik.http.services.calibre-vnc.loadbalancer.server.port: 8080
      traefik.http.routers.calibre-vnc.middlewares: authentik@docker

      glance.name: Calibre
      glance.icon: sh:calibre
      glance.url: https://${SERVICE_URL_CALIBRE_VNC}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/calibre.png
      net.unraid.docker.webui: https://${SERVICE_URL_CALIBRE_VNC}

networks:
  proxy:
    external: true