apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingress
  namespace: argocd
  labels:
    name: argocd-ingress
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`argocd.domain.com`)
    kind: Rule
    services:
    - name: argocd-server
      port: http