version: '3'
services:
  portainer:
    image: portainer/portainer-ce:2.11.1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.joost.io`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    networks:
      - traefik

volumes:
  portainer_data:

networks:
  traefik:
    external: true