version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.portainer_https.entrypoints=websecure"
      - "traefik.http.routers.portainer_https.rule=Host(`portainer.joost.io`)"
      - "traefik.http.routers.portainer_https.tls=true"
      - "traefik.http.routers.portainer_https.tls.certresolver=myresolver"
      - "traefik.http.routers.portainer_https.service=portainer"

      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik

networks:
  traefik:
    external: true