version: "3.4"
services:
  unifi:
    image: jacobalberty/unifi:stable-6
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - "3478:3478"
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./data/run:/var/run/unifi
      - ./data/unifi:/unifi
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.unifi_https.entrypoints=websecure"
      - "traefik.http.routers.unifi_https.rule=Host(`unifi.joost.io`)"
      - "traefik.http.routers.unifi_https.tls=true"
      - "traefik.http.routers.unifi_https.tls.certresolver=myresolver"
      - "traefik.http.routers.unifi_https.service=unifi"

      - "traefik.http.services.unifi.loadbalancer.server.port=8443"
      - "traefik.http.services.unifi.loadbalancer.server.scheme=https"

      - "com.centurylinklabs.watchtower.enable=true"
  
networks:
  traefik:
    external: true