services:
  paperless:
    container_name: paperless
    image: ghcr.io/paperless-ngx/paperless-ngx:2.19.0
    restart: always
    volumes:
      - ${APPDATA_PATH}/paperless-ngx/data:/usr/src/paperless/data
      - ${MNT_PATH}/paperless/media:/usr/src/paperless/media
      - ${MNT_PATH}/paperless_consume/:/usr/src/paperless/consume
      - ${MNT_PATH}/paperless/export/:/usr/src/paperless/export
    env_file: .env
    networks:
      - proxy
      - redis_net
    labels:
      traefik.enable: true
      traefik.http.routers.paperless.tls: true
      traefik.http.routers.paperless.tls.certresolver: letsencrypt
      traefik.http.routers.paperless.rule: Host(`${SERVICE_URL}`)
      traefik.http.routers.paperless.entrypoints: websecure

      glance.name: Paperless
      glance.icon: sh:paperless-ngx
      glance.url: https://${SERVICE_URL}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/paperless-ngx.png
      net.unraid.docker.webui: https://${SERVICE_URL}
networks:
  proxy:
    external: true
  redis_net:
    external: true
