[[stack]]
name = "paperless"
[stack.config]
server = "nas"
linked_repo = "selfhosted"
run_directory = "services/paperless"
file_paths = ["docker-compose.yml"]
environment = """
DOMAIN=[[DOMAIN]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
UMASK=[[UMASK]]
MNT_PATH=[[MNT_PATH]]
APPDATA_PATH=[[APPDATA_PATH]]
DATA_PATH=[[DATA_PATH]]

PAPERLESS_REDIS=redis://redis:6379
PAPERLESS_OCR_LANGUAGE=deu
PAPERLESS_TIME_ZONE=${TZ}
PAPERLESS_CONSUMER_ENABLE_BARCODES=1
PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE=1
PAPERLESS_URL=https://paperless.${DOMAIN}
PAPERLESS_SECRET_KEY=[[PAPERLESS_SECRET_KEY]]

SERVICE_URL=paperless.[[DOMAIN]]
"""