version: "3.4"

services:
  app:
    image: monica
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./data/www:/var/www/html/storage
    restart: always
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.monica_https.entrypoints=websecure"
      - "traefik.http.routers.monica_https.rule=Host(`monica.joost.io`)"
      - "traefik.http.routers.monica_https.tls=true"
      - "traefik.http.routers.monica_https.tls.certresolver=myresolver"
      - "traefik.http.routers.monica_https.service=monica"
      
      - "traefik.http.services.monica.loadbalancer.server.port=80"

      - "com.centurylinklabs.watchtower.enable=true"

  cron:
    image: monica
    env_file: .env
    restart: always
    volumes:
      - ./data/www:/var/www/html/storage
    command: cron.sh
    networks:
      - default
    depends_on:
      - db

  db:
    image: jsurf/rpi-mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: monica
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    networks:
      - default
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
  traefik:
    external: true