version: "3"
services:
  db_recipes:
    restart: unless-stopped
    image: postgres:11-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - default

  web_recipes:
    image: vabene1111/recipes
    restart: unless-stopped
    volumes:
      - ./data/static:/opt/recipes/staticfiles
      - ./data/media:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.tandoor_https.entrypoints=websecure"
      - "traefik.http.routers.tandoor_https.rule=Host(`tandoor.joost.io`)"
      - "traefik.http.routers.tandoor_https.tls=true"
      - "traefik.http.routers.tandoor_https.tls.certresolver=myresolver"
      - "traefik.http.routers.tandoor_https.service=tandoor"

      - "traefik.http.services.tandoor.loadbalancer.server.port=8080"

      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - default
      - traefik
      
networks:
  default:
  traefik:
    external: true

