version: "2.4"
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: filebrowser
    volumes:
      - ./data/files:/srv
      - ./data/database:/database
      - ./.filebrowser.json:/.filebrowser.json
    environment:
      TZ: Europe/Berlin
networks:
  default:
    external: true
    name: npm
