[[stack]]
name = "tandoor"
[stack.config]
server = "nas"
linked_repo = "selfhosted"
run_directory = "services/tandoor"
file_paths = ["docker-compose.yml"]
environment = """
APPDATA_PATH=[[APPDATA_PATH]]
TZ=[[TZ]]
SERVICE_URL=recipes.[[DOMAIN]]

DB_ENGINE=django.db.backends.sqlite3
SECRET_KEY=[[TANDOOR_SECRET_KEY]]
ALLOWED_HOSTS=${SERVICE_URL}
POSTGRES_DB=/data/recipes.db
GUNICORN_MEDIA=1
GUNICORN_WORKERS=1
GUNICORN_THREADS=1
"""